services:
  db_training:
    image: postgres:14-alpine
    container_name: db_training
    environment:
      POSTGRES_USER: ${POSTGRES_TRAINING_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TRAINING_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TRAINING_DB}
    volumes:
      - db_training_vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_TRAINING_USER} -d ${POSTGRES_TRAINING_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - training_net

  cache:
    image: redis:7-alpine
    container_name: cache
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped
    networks:
      - training_net
  nats-js:
    image: nats:latest
    container_name: nats-js
    ports:
      - "${NATS_PORT}:4222"
      - "${HEALTH_CHECK_PORT}:8222"
    command: [ "-js", "-sd", "/data/jetstream" ]
    volumes:
      - nats_vol:/data/jetstream
    restart: unless-stopped
    networks:
      - training_net

  training:
      container_name: training
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - ${TRAINING_PORT}:9045
      environment:
        CONFIG_PATH: config/docker.yaml
        LLM_API_KEY: ${LLM_API_KEY}
      depends_on:
        db_training:
          condition: service_healthy
      restart: unless-stopped
      networks:
        - training_net
networks:
  training_net:

volumes:
  db_training_vol:
    driver: local
  nats_vol:
    driver: local
