// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "trainers-manager/internal/entity"
	dto "trainers-manager/internal/usecase/dto"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTrainingStructureRepo is a mock of TrainingStructureRepo interface.
type MockTrainingStructureRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingStructureRepoMockRecorder
	isgomock struct{}
}

// MockTrainingStructureRepoMockRecorder is the mock recorder for MockTrainingStructureRepo.
type MockTrainingStructureRepoMockRecorder struct {
	mock *MockTrainingStructureRepo
}

// NewMockTrainingStructureRepo creates a new mock instance.
func NewMockTrainingStructureRepo(ctrl *gomock.Controller) *MockTrainingStructureRepo {
	mock := &MockTrainingStructureRepo{ctrl: ctrl}
	mock.recorder = &MockTrainingStructureRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingStructureRepo) EXPECT() *MockTrainingStructureRepoMockRecorder {
	return m.recorder
}

// CreateStructure mocks base method.
func (m *MockTrainingStructureRepo) CreateStructure(arg0 context.Context, arg1 entity.TrainingStructure) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStructure", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStructure indicates an expected call of CreateStructure.
func (mr *MockTrainingStructureRepoMockRecorder) CreateStructure(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStructure", reflect.TypeOf((*MockTrainingStructureRepo)(nil).CreateStructure), arg0, arg1)
}

// DeleteStructure mocks base method.
func (m *MockTrainingStructureRepo) DeleteStructure(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStructure", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStructure indicates an expected call of DeleteStructure.
func (mr *MockTrainingStructureRepoMockRecorder) DeleteStructure(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStructure", reflect.TypeOf((*MockTrainingStructureRepo)(nil).DeleteStructure), arg0, arg1)
}

// GetStructure mocks base method.
func (m *MockTrainingStructureRepo) GetStructure(arg0 context.Context, arg1 uuid.UUID) (entity.TrainingStructure, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructure", arg0, arg1)
	ret0, _ := ret[0].(entity.TrainingStructure)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStructure indicates an expected call of GetStructure.
func (mr *MockTrainingStructureRepoMockRecorder) GetStructure(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructure", reflect.TypeOf((*MockTrainingStructureRepo)(nil).GetStructure), arg0, arg1)
}

// ListStructure mocks base method.
func (m *MockTrainingStructureRepo) ListStructure(arg0 context.Context) ([]entity.TrainingStructure, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStructure", arg0)
	ret0, _ := ret[0].([]entity.TrainingStructure)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStructure indicates an expected call of ListStructure.
func (mr *MockTrainingStructureRepoMockRecorder) ListStructure(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStructure", reflect.TypeOf((*MockTrainingStructureRepo)(nil).ListStructure), arg0)
}

// UpdateStructure mocks base method.
func (m *MockTrainingStructureRepo) UpdateStructure(arg0 context.Context, arg1 entity.TrainingStructure, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStructure", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStructure indicates an expected call of UpdateStructure.
func (mr *MockTrainingStructureRepoMockRecorder) UpdateStructure(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStructure", reflect.TypeOf((*MockTrainingStructureRepo)(nil).UpdateStructure), arg0, arg1, arg2)
}

// MockExerciseRepo is a mock of ExerciseRepo interface.
type MockExerciseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExerciseRepoMockRecorder
	isgomock struct{}
}

// MockExerciseRepoMockRecorder is the mock recorder for MockExerciseRepo.
type MockExerciseRepoMockRecorder struct {
	mock *MockExerciseRepo
}

// NewMockExerciseRepo creates a new mock instance.
func NewMockExerciseRepo(ctrl *gomock.Controller) *MockExerciseRepo {
	mock := &MockExerciseRepo{ctrl: ctrl}
	mock.recorder = &MockExerciseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExerciseRepo) EXPECT() *MockExerciseRepoMockRecorder {
	return m.recorder
}

// CreateExercise mocks base method.
func (m *MockExerciseRepo) CreateExercise(arg0 context.Context, arg1 entity.Exercise) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExercise", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExercise indicates an expected call of CreateExercise.
func (mr *MockExerciseRepoMockRecorder) CreateExercise(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExercise", reflect.TypeOf((*MockExerciseRepo)(nil).CreateExercise), arg0, arg1)
}

// DeleteExercise mocks base method.
func (m *MockExerciseRepo) DeleteExercise(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExercise", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExercise indicates an expected call of DeleteExercise.
func (mr *MockExerciseRepoMockRecorder) DeleteExercise(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExercise", reflect.TypeOf((*MockExerciseRepo)(nil).DeleteExercise), arg0, arg1)
}

// ListExercises mocks base method.
func (m *MockExerciseRepo) ListExercises(arg0 context.Context) ([]entity.Exercise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExercises", arg0)
	ret0, _ := ret[0].([]entity.Exercise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExercises indicates an expected call of ListExercises.
func (mr *MockExerciseRepoMockRecorder) ListExercises(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExercises", reflect.TypeOf((*MockExerciseRepo)(nil).ListExercises), arg0)
}

// UpdateExercise mocks base method.
func (m *MockExerciseRepo) UpdateExercise(arg0 context.Context, arg1 dto.UpdateExerciseInput, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExercise", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExercise indicates an expected call of UpdateExercise.
func (mr *MockExerciseRepoMockRecorder) UpdateExercise(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExercise", reflect.TypeOf((*MockExerciseRepo)(nil).UpdateExercise), arg0, arg1, arg2)
}

// MockTrainingRepo is a mock of TrainingRepo interface.
type MockTrainingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingRepoMockRecorder
	isgomock struct{}
}

// MockTrainingRepoMockRecorder is the mock recorder for MockTrainingRepo.
type MockTrainingRepoMockRecorder struct {
	mock *MockTrainingRepo
}

// NewMockTrainingRepo creates a new mock instance.
func NewMockTrainingRepo(ctrl *gomock.Controller) *MockTrainingRepo {
	mock := &MockTrainingRepo{ctrl: ctrl}
	mock.recorder = &MockTrainingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingRepo) EXPECT() *MockTrainingRepoMockRecorder {
	return m.recorder
}

// CreateTraining mocks base method.
func (m *MockTrainingRepo) CreateTraining(arg0 context.Context) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTraining", arg0)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTraining indicates an expected call of CreateTraining.
func (mr *MockTrainingRepoMockRecorder) CreateTraining(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTraining", reflect.TypeOf((*MockTrainingRepo)(nil).CreateTraining), arg0)
}

// MockTrainingPlanRepo is a mock of TrainingPlanRepo interface.
type MockTrainingPlanRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingPlanRepoMockRecorder
	isgomock struct{}
}

// MockTrainingPlanRepoMockRecorder is the mock recorder for MockTrainingPlanRepo.
type MockTrainingPlanRepoMockRecorder struct {
	mock *MockTrainingPlanRepo
}

// NewMockTrainingPlanRepo creates a new mock instance.
func NewMockTrainingPlanRepo(ctrl *gomock.Controller) *MockTrainingPlanRepo {
	mock := &MockTrainingPlanRepo{ctrl: ctrl}
	mock.recorder = &MockTrainingPlanRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingPlanRepo) EXPECT() *MockTrainingPlanRepoMockRecorder {
	return m.recorder
}

// GetTrainingPlan mocks base method.
func (m *MockTrainingPlanRepo) GetTrainingPlan(arg0 context.Context, arg1 uuid.UUID) (entity.TrainingPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrainingPlan", arg0, arg1)
	ret0, _ := ret[0].(entity.TrainingPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrainingPlan indicates an expected call of GetTrainingPlan.
func (mr *MockTrainingPlanRepoMockRecorder) GetTrainingPlan(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrainingPlan", reflect.TypeOf((*MockTrainingPlanRepo)(nil).GetTrainingPlan), arg0, arg1)
}

// ListTrainingPlan mocks base method.
func (m *MockTrainingPlanRepo) ListTrainingPlan(arg0 context.Context) ([]entity.TrainingPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrainingPlan", arg0)
	ret0, _ := ret[0].([]entity.TrainingPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrainingPlan indicates an expected call of ListTrainingPlan.
func (mr *MockTrainingPlanRepoMockRecorder) ListTrainingPlan(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrainingPlan", reflect.TypeOf((*MockTrainingPlanRepo)(nil).ListTrainingPlan), arg0)
}

// StoreTrainingPlan mocks base method.
func (m *MockTrainingPlanRepo) StoreTrainingPlan(arg0 context.Context, arg1 entity.TrainingPlan) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTrainingPlan", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreTrainingPlan indicates an expected call of StoreTrainingPlan.
func (mr *MockTrainingPlanRepoMockRecorder) StoreTrainingPlan(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTrainingPlan", reflect.TypeOf((*MockTrainingPlanRepo)(nil).StoreTrainingPlan), arg0, arg1)
}

// UpdateTrainingPlan mocks base method.
func (m *MockTrainingPlanRepo) UpdateTrainingPlan(arg0 context.Context, arg1 entity.TrainingPlan, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrainingPlan", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrainingPlan indicates an expected call of UpdateTrainingPlan.
func (mr *MockTrainingPlanRepoMockRecorder) UpdateTrainingPlan(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrainingPlan", reflect.TypeOf((*MockTrainingPlanRepo)(nil).UpdateTrainingPlan), arg0, arg1, arg2)
}

// MockPlanHistoryRepo is a mock of PlanHistoryRepo interface.
type MockPlanHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPlanHistoryRepoMockRecorder
	isgomock struct{}
}

// MockPlanHistoryRepoMockRecorder is the mock recorder for MockPlanHistoryRepo.
type MockPlanHistoryRepoMockRecorder struct {
	mock *MockPlanHistoryRepo
}

// NewMockPlanHistoryRepo creates a new mock instance.
func NewMockPlanHistoryRepo(ctrl *gomock.Controller) *MockPlanHistoryRepo {
	mock := &MockPlanHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockPlanHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanHistoryRepo) EXPECT() *MockPlanHistoryRepoMockRecorder {
	return m.recorder
}

// GetPlanHistory mocks base method.
func (m *MockPlanHistoryRepo) GetPlanHistory(arg0 context.Context, arg1 uuid.UUID) ([]entity.TrainingPlanHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanHistory", arg0, arg1)
	ret0, _ := ret[0].([]entity.TrainingPlanHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanHistory indicates an expected call of GetPlanHistory.
func (mr *MockPlanHistoryRepoMockRecorder) GetPlanHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanHistory", reflect.TypeOf((*MockPlanHistoryRepo)(nil).GetPlanHistory), arg0, arg1)
}

// MockTrainingGroupRepo is a mock of TrainingGroupRepo interface.
type MockTrainingGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingGroupRepoMockRecorder
	isgomock struct{}
}

// MockTrainingGroupRepoMockRecorder is the mock recorder for MockTrainingGroupRepo.
type MockTrainingGroupRepoMockRecorder struct {
	mock *MockTrainingGroupRepo
}

// NewMockTrainingGroupRepo creates a new mock instance.
func NewMockTrainingGroupRepo(ctrl *gomock.Controller) *MockTrainingGroupRepo {
	mock := &MockTrainingGroupRepo{ctrl: ctrl}
	mock.recorder = &MockTrainingGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrainingGroupRepo) EXPECT() *MockTrainingGroupRepoMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockTrainingGroupRepo) CreateGroup(arg0 context.Context, arg1 entity.TrainingGroup) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockTrainingGroupRepoMockRecorder) CreateGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockTrainingGroupRepo)(nil).CreateGroup), arg0, arg1)
}

// DeleteGroup mocks base method.
func (m *MockTrainingGroupRepo) DeleteGroup(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockTrainingGroupRepoMockRecorder) DeleteGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockTrainingGroupRepo)(nil).DeleteGroup), arg0, arg1)
}

// GetGroupByName mocks base method.
func (m *MockTrainingGroupRepo) GetGroupByName(arg0 context.Context, arg1 string) (entity.TrainingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", arg0, arg1)
	ret0, _ := ret[0].(entity.TrainingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockTrainingGroupRepoMockRecorder) GetGroupByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockTrainingGroupRepo)(nil).GetGroupByName), arg0, arg1)
}

// ListGroups mocks base method.
func (m *MockTrainingGroupRepo) ListGroups(arg0 context.Context) ([]entity.TrainingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", arg0)
	ret0, _ := ret[0].([]entity.TrainingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockTrainingGroupRepoMockRecorder) ListGroups(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockTrainingGroupRepo)(nil).ListGroups), arg0)
}

// UpdateGroup mocks base method.
func (m *MockTrainingGroupRepo) UpdateGroup(arg0 context.Context, arg1 dto.UpdateGroupInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockTrainingGroupRepoMockRecorder) UpdateGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockTrainingGroupRepo)(nil).UpdateGroup), arg0, arg1)
}

// MockGenerationRepo is a mock of GenerationRepo interface.
type MockGenerationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGenerationRepoMockRecorder
	isgomock struct{}
}

// MockGenerationRepoMockRecorder is the mock recorder for MockGenerationRepo.
type MockGenerationRepoMockRecorder struct {
	mock *MockGenerationRepo
}

// NewMockGenerationRepo creates a new mock instance.
func NewMockGenerationRepo(ctrl *gomock.Controller) *MockGenerationRepo {
	mock := &MockGenerationRepo{ctrl: ctrl}
	mock.recorder = &MockGenerationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerationRepo) EXPECT() *MockGenerationRepoMockRecorder {
	return m.recorder
}

// CreateTraining mocks base method.
func (m *MockGenerationRepo) CreateTraining(arg0 context.Context) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTraining", arg0)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTraining indicates an expected call of CreateTraining.
func (mr *MockGenerationRepoMockRecorder) CreateTraining(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTraining", reflect.TypeOf((*MockGenerationRepo)(nil).CreateTraining), arg0)
}

// GetGroupByName mocks base method.
func (m *MockGenerationRepo) GetGroupByName(arg0 context.Context, arg1 string) (entity.TrainingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", arg0, arg1)
	ret0, _ := ret[0].(entity.TrainingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockGenerationRepoMockRecorder) GetGroupByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockGenerationRepo)(nil).GetGroupByName), arg0, arg1)
}

// GetStructure mocks base method.
func (m *MockGenerationRepo) GetStructure(arg0 context.Context, arg1 uuid.UUID) (entity.TrainingStructure, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructure", arg0, arg1)
	ret0, _ := ret[0].(entity.TrainingStructure)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStructure indicates an expected call of GetStructure.
func (mr *MockGenerationRepoMockRecorder) GetStructure(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructure", reflect.TypeOf((*MockGenerationRepo)(nil).GetStructure), arg0, arg1)
}

// LinkExercises mocks base method.
func (m *MockGenerationRepo) LinkExercises(arg0 context.Context, arg1 uuid.UUID, arg2 []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkExercises", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkExercises indicates an expected call of LinkExercises.
func (mr *MockGenerationRepoMockRecorder) LinkExercises(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkExercises", reflect.TypeOf((*MockGenerationRepo)(nil).LinkExercises), arg0, arg1, arg2)
}

// ListExercises mocks base method.
func (m *MockGenerationRepo) ListExercises(arg0 context.Context) ([]entity.Exercise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExercises", arg0)
	ret0, _ := ret[0].([]entity.Exercise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExercises indicates an expected call of ListExercises.
func (mr *MockGenerationRepoMockRecorder) ListExercises(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExercises", reflect.TypeOf((*MockGenerationRepo)(nil).ListExercises), arg0)
}

// RecentPlans mocks base method.
func (m *MockGenerationRepo) RecentPlans(arg0 context.Context, arg1 uuid.UUID, arg2 int) ([]entity.TrainingPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentPlans", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entity.TrainingPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentPlans indicates an expected call of RecentPlans.
func (mr *MockGenerationRepoMockRecorder) RecentPlans(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentPlans", reflect.TypeOf((*MockGenerationRepo)(nil).RecentPlans), arg0, arg1, arg2)
}

// StoreTrainingPlan mocks base method.
func (m *MockGenerationRepo) StoreTrainingPlan(arg0 context.Context, arg1 entity.TrainingPlan) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTrainingPlan", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreTrainingPlan indicates an expected call of StoreTrainingPlan.
func (mr *MockGenerationRepoMockRecorder) StoreTrainingPlan(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTrainingPlan", reflect.TypeOf((*MockGenerationRepo)(nil).StoreTrainingPlan), arg0, arg1)
}

// MockPartitionsRepo is a mock of PartitionsRepo interface.
type MockPartitionsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPartitionsRepoMockRecorder
	isgomock struct{}
}

// MockPartitionsRepoMockRecorder is the mock recorder for MockPartitionsRepo.
type MockPartitionsRepoMockRecorder struct {
	mock *MockPartitionsRepo
}

// NewMockPartitionsRepo creates a new mock instance.
func NewMockPartitionsRepo(ctrl *gomock.Controller) *MockPartitionsRepo {
	mock := &MockPartitionsRepo{ctrl: ctrl}
	mock.recorder = &MockPartitionsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartitionsRepo) EXPECT() *MockPartitionsRepoMockRecorder {
	return m.recorder
}

// EnsureHistoryPartitions mocks base method.
func (m *MockPartitionsRepo) EnsureHistoryPartitions(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureHistoryPartitions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureHistoryPartitions indicates an expected call of EnsureHistoryPartitions.
func (mr *MockPartitionsRepoMockRecorder) EnsureHistoryPartitions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureHistoryPartitions", reflect.TypeOf((*MockPartitionsRepo)(nil).EnsureHistoryPartitions), arg0, arg1)
}
