// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "trainers-manager/internal/entity"
	usecase "trainers-manager/internal/usecase"
	dto "trainers-manager/internal/usecase/dto"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStructure is a mock of Structure interface.
type MockStructure struct {
	ctrl     *gomock.Controller
	recorder *MockStructureMockRecorder
	isgomock struct{}
}

// MockStructureMockRecorder is the mock recorder for MockStructure.
type MockStructureMockRecorder struct {
	mock *MockStructure
}

// NewMockStructure creates a new mock instance.
func NewMockStructure(ctrl *gomock.Controller) *MockStructure {
	mock := &MockStructure{ctrl: ctrl}
	mock.recorder = &MockStructureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStructure) EXPECT() *MockStructureMockRecorder {
	return m.recorder
}

// CreateStructure mocks base method.
func (m *MockStructure) CreateStructure(arg0 context.Context, arg1 entity.TrainingStructure) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStructure", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStructure indicates an expected call of CreateStructure.
func (mr *MockStructureMockRecorder) CreateStructure(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStructure", reflect.TypeOf((*MockStructure)(nil).CreateStructure), arg0, arg1)
}

// DeleteStructure mocks base method.
func (m *MockStructure) DeleteStructure(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStructure", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStructure indicates an expected call of DeleteStructure.
func (mr *MockStructureMockRecorder) DeleteStructure(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStructure", reflect.TypeOf((*MockStructure)(nil).DeleteStructure), arg0, arg1)
}

// GetStructure mocks base method.
func (m *MockStructure) GetStructure(arg0 context.Context, arg1 uuid.UUID) (entity.TrainingStructure, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructure", arg0, arg1)
	ret0, _ := ret[0].(entity.TrainingStructure)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStructure indicates an expected call of GetStructure.
func (mr *MockStructureMockRecorder) GetStructure(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructure", reflect.TypeOf((*MockStructure)(nil).GetStructure), arg0, arg1)
}

// ListStructure mocks base method.
func (m *MockStructure) ListStructure(arg0 context.Context) ([]entity.TrainingStructure, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStructure", arg0)
	ret0, _ := ret[0].([]entity.TrainingStructure)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStructure indicates an expected call of ListStructure.
func (mr *MockStructureMockRecorder) ListStructure(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStructure", reflect.TypeOf((*MockStructure)(nil).ListStructure), arg0)
}

// UpdateStructure mocks base method.
func (m *MockStructure) UpdateStructure(arg0 context.Context, arg1 entity.TrainingStructure, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStructure", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStructure indicates an expected call of UpdateStructure.
func (mr *MockStructureMockRecorder) UpdateStructure(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStructure", reflect.TypeOf((*MockStructure)(nil).UpdateStructure), arg0, arg1, arg2)
}

// MockExercise is a mock of Exercise interface.
type MockExercise struct {
	ctrl     *gomock.Controller
	recorder *MockExerciseMockRecorder
	isgomock struct{}
}

// MockExerciseMockRecorder is the mock recorder for MockExercise.
type MockExerciseMockRecorder struct {
	mock *MockExercise
}

// NewMockExercise creates a new mock instance.
func NewMockExercise(ctrl *gomock.Controller) *MockExercise {
	mock := &MockExercise{ctrl: ctrl}
	mock.recorder = &MockExerciseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExercise) EXPECT() *MockExerciseMockRecorder {
	return m.recorder
}

// CreateExercise mocks base method.
func (m *MockExercise) CreateExercise(arg0 context.Context, arg1 entity.Exercise) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExercise", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExercise indicates an expected call of CreateExercise.
func (mr *MockExerciseMockRecorder) CreateExercise(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExercise", reflect.TypeOf((*MockExercise)(nil).CreateExercise), arg0, arg1)
}

// DeleteExercise mocks base method.
func (m *MockExercise) DeleteExercise(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExercise", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExercise indicates an expected call of DeleteExercise.
func (mr *MockExerciseMockRecorder) DeleteExercise(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExercise", reflect.TypeOf((*MockExercise)(nil).DeleteExercise), arg0, arg1)
}

// ListExercises mocks base method.
func (m *MockExercise) ListExercises(arg0 context.Context) ([]entity.Exercise, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExercises", arg0)
	ret0, _ := ret[0].([]entity.Exercise)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExercises indicates an expected call of ListExercises.
func (mr *MockExerciseMockRecorder) ListExercises(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExercises", reflect.TypeOf((*MockExercise)(nil).ListExercises), arg0)
}

// UpdateExercise mocks base method.
func (m *MockExercise) UpdateExercise(arg0 context.Context, arg1 dto.UpdateExerciseInput, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExercise", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExercise indicates an expected call of UpdateExercise.
func (mr *MockExerciseMockRecorder) UpdateExercise(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExercise", reflect.TypeOf((*MockExercise)(nil).UpdateExercise), arg0, arg1, arg2)
}

// MockTraining is a mock of Training interface.
type MockTraining struct {
	ctrl     *gomock.Controller
	recorder *MockTrainingMockRecorder
	isgomock struct{}
}

// MockTrainingMockRecorder is the mock recorder for MockTraining.
type MockTrainingMockRecorder struct {
	mock *MockTraining
}

// NewMockTraining creates a new mock instance.
func NewMockTraining(ctrl *gomock.Controller) *MockTraining {
	mock := &MockTraining{ctrl: ctrl}
	mock.recorder = &MockTrainingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTraining) EXPECT() *MockTrainingMockRecorder {
	return m.recorder
}

// CreateTraining mocks base method.
func (m *MockTraining) CreateTraining(arg0 context.Context) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTraining", arg0)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTraining indicates an expected call of CreateTraining.
func (mr *MockTrainingMockRecorder) CreateTraining(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTraining", reflect.TypeOf((*MockTraining)(nil).CreateTraining), arg0)
}

// MockPlan is a mock of Plan interface.
type MockPlan struct {
	ctrl     *gomock.Controller
	recorder *MockPlanMockRecorder
	isgomock struct{}
}

// MockPlanMockRecorder is the mock recorder for MockPlan.
type MockPlanMockRecorder struct {
	mock *MockPlan
}

// NewMockPlan creates a new mock instance.
func NewMockPlan(ctrl *gomock.Controller) *MockPlan {
	mock := &MockPlan{ctrl: ctrl}
	mock.recorder = &MockPlanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlan) EXPECT() *MockPlanMockRecorder {
	return m.recorder
}

// GetTrainingPlan mocks base method.
func (m *MockPlan) GetTrainingPlan(arg0 context.Context, arg1 uuid.UUID) (entity.TrainingPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrainingPlan", arg0, arg1)
	ret0, _ := ret[0].(entity.TrainingPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrainingPlan indicates an expected call of GetTrainingPlan.
func (mr *MockPlanMockRecorder) GetTrainingPlan(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrainingPlan", reflect.TypeOf((*MockPlan)(nil).GetTrainingPlan), arg0, arg1)
}

// ListTrainingPlan mocks base method.
func (m *MockPlan) ListTrainingPlan(arg0 context.Context) ([]entity.TrainingPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrainingPlan", arg0)
	ret0, _ := ret[0].([]entity.TrainingPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrainingPlan indicates an expected call of ListTrainingPlan.
func (mr *MockPlanMockRecorder) ListTrainingPlan(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrainingPlan", reflect.TypeOf((*MockPlan)(nil).ListTrainingPlan), arg0)
}

// StoreTrainingPlan mocks base method.
func (m *MockPlan) StoreTrainingPlan(arg0 context.Context, arg1 entity.TrainingPlan) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTrainingPlan", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreTrainingPlan indicates an expected call of StoreTrainingPlan.
func (mr *MockPlanMockRecorder) StoreTrainingPlan(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTrainingPlan", reflect.TypeOf((*MockPlan)(nil).StoreTrainingPlan), arg0, arg1)
}

// UpdateTrainingPlan mocks base method.
func (m *MockPlan) UpdateTrainingPlan(arg0 context.Context, arg1 entity.TrainingPlan, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrainingPlan", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrainingPlan indicates an expected call of UpdateTrainingPlan.
func (mr *MockPlanMockRecorder) UpdateTrainingPlan(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrainingPlan", reflect.TypeOf((*MockPlan)(nil).UpdateTrainingPlan), arg0, arg1, arg2)
}

// MockPlanHistory is a mock of PlanHistory interface.
type MockPlanHistory struct {
	ctrl     *gomock.Controller
	recorder *MockPlanHistoryMockRecorder
	isgomock struct{}
}

// MockPlanHistoryMockRecorder is the mock recorder for MockPlanHistory.
type MockPlanHistoryMockRecorder struct {
	mock *MockPlanHistory
}

// NewMockPlanHistory creates a new mock instance.
func NewMockPlanHistory(ctrl *gomock.Controller) *MockPlanHistory {
	mock := &MockPlanHistory{ctrl: ctrl}
	mock.recorder = &MockPlanHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanHistory) EXPECT() *MockPlanHistoryMockRecorder {
	return m.recorder
}

// GetPlanHistory mocks base method.
func (m *MockPlanHistory) GetPlanHistory(arg0 context.Context, arg1 uuid.UUID) ([]entity.TrainingPlanHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanHistory", arg0, arg1)
	ret0, _ := ret[0].([]entity.TrainingPlanHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanHistory indicates an expected call of GetPlanHistory.
func (mr *MockPlanHistoryMockRecorder) GetPlanHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanHistory", reflect.TypeOf((*MockPlanHistory)(nil).GetPlanHistory), arg0, arg1)
}

// MockGroup is a mock of Group interface.
type MockGroup struct {
	ctrl     *gomock.Controller
	recorder *MockGroupMockRecorder
	isgomock struct{}
}

// MockGroupMockRecorder is the mock recorder for MockGroup.
type MockGroupMockRecorder struct {
	mock *MockGroup
}

// NewMockGroup creates a new mock instance.
func NewMockGroup(ctrl *gomock.Controller) *MockGroup {
	mock := &MockGroup{ctrl: ctrl}
	mock.recorder = &MockGroupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroup) EXPECT() *MockGroupMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockGroup) CreateGroup(arg0 context.Context, arg1 entity.TrainingGroup) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupMockRecorder) CreateGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroup)(nil).CreateGroup), arg0, arg1)
}

// DeleteGroup mocks base method.
func (m *MockGroup) DeleteGroup(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupMockRecorder) DeleteGroup(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroup)(nil).DeleteGroup), arg0, arg1)
}

// GetGroupByName mocks base method.
func (m *MockGroup) GetGroupByName(arg0 context.Context, arg1 string) (entity.TrainingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", arg0, arg1)
	ret0, _ := ret[0].(entity.TrainingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockGroupMockRecorder) GetGroupByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockGroup)(nil).GetGroupByName), arg0, arg1)
}

// ListGroups mocks base method.
func (m *MockGroup) ListGroups(arg0 context.Context) ([]entity.TrainingGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", arg0)
	ret0, _ := ret[0].([]entity.TrainingGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupMockRecorder) ListGroups(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroup)(nil).ListGroups), arg0)
}

// UpdateGroup mocks base method.
func (m *MockGroup) UpdateGroup(arg0 context.Context, arg1 entity.TrainingGroup, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupMockRecorder) UpdateGroup(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroup)(nil).UpdateGroup), arg0, arg1, arg2)
}

// MockGenerate is a mock of Generate interface.
type MockGenerate struct {
	ctrl     *gomock.Controller
	recorder *MockGenerateMockRecorder
	isgomock struct{}
}

// MockGenerateMockRecorder is the mock recorder for MockGenerate.
type MockGenerateMockRecorder struct {
	mock *MockGenerate
}

// NewMockGenerate creates a new mock instance.
func NewMockGenerate(ctrl *gomock.Controller) *MockGenerate {
	mock := &MockGenerate{ctrl: ctrl}
	mock.recorder = &MockGenerateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerate) EXPECT() *MockGenerateMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockGenerate) Generate(ctx context.Context, trainType string, structureID uuid.UUID) (entity.TrainingPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, trainType, structureID)
	ret0, _ := ret[0].(entity.TrainingPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockGenerateMockRecorder) Generate(ctx, trainType, structureID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockGenerate)(nil).Generate), ctx, trainType, structureID)
}

// MockPlanGenerator is a mock of PlanGenerator interface.
type MockPlanGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockPlanGeneratorMockRecorder
	isgomock struct{}
}

// MockPlanGeneratorMockRecorder is the mock recorder for MockPlanGenerator.
type MockPlanGeneratorMockRecorder struct {
	mock *MockPlanGenerator
}

// NewMockPlanGenerator creates a new mock instance.
func NewMockPlanGenerator(ctrl *gomock.Controller) *MockPlanGenerator {
	mock := &MockPlanGenerator{ctrl: ctrl}
	mock.recorder = &MockPlanGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanGenerator) EXPECT() *MockPlanGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockPlanGenerator) Generate(ctx context.Context, in usecase.GeneratePrompt) (usecase.GeneratedPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, in)
	ret0, _ := ret[0].(usecase.GeneratedPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockPlanGeneratorMockRecorder) Generate(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockPlanGenerator)(nil).Generate), ctx, in)
}
